//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ToDoList
    {
        public long ToDoID { get; set; }
        [Required(ErrorMessage ="Please Enter Task Name.")]
        public string ToDoName { get; set; }
        [Required(ErrorMessage = "Please Enter Task Description.")]
        public string ToDoDescription { get; set; }
        [Required(ErrorMessage = "Please Select Due Date.")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime CreationDate { get; set; }
        [Required(ErrorMessage = "Please Choose Priority.")]
        public string Priority { get; set; }
        public bool Status { get; set; }
        public byte[] Image { get; set; }
    }
}
